config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :tasks, except: [:show]
  resources :emails, except: [:edit]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/email.rb
class Email < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	add_flash_types :success, :error
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
	def index
		@emails = Email.all
	end

	def create
		@email = Email.new(object:Faker::Hipster.sentence(word_count: 2),
		body:Faker::Hipster.paragraph(sentence_count: 2,
			supplemental: true, random_sentences_to_add: 4), read: false)
			@email.save
		respond_to do |format|
			format.html{
			redirect_to emails_path, notice: "created successfull"	
			}
			format.js{

			}
		end
		
	end

	def show
		@email = find_email
		respond_to do |format|
			format.html{}
			format.js{}
		end


	end
	def destroy
		@email= find_email
		@email.destroy
		respond_to do |format|
			format.html{
			redirect_to emails_path, success: "Deleted successfull"
			}
			format.js{}
		end
		
	end

	def update
		@email = find_email
		if @email.read === false
			@email.update(read: true)
		else
			@email.update(read: false)
		end

		respond_to do |format|
				format.html{}
				format.js{}
		end
	end
	private
	def find_email
		Email.find(params[:id])
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :authenticate_user!
  def new
    @categories = Category.all
  end

  def create
    @task = Task.new(task_params)
    @category = Category.find(category_params)
    @task.category = @category

    respond_to do |format|
      if @task.save
        format.html{
        redirect_to root_path
        flash[:notice] = "Task created"
        }
        format.js{}  
      else
        format.html{
        redirect_to root_path
        flash[:notice] = "Please try again"
        }
      end
    end
  end

  def edit
    @task = Task.find(params[:id])
    @categories = Category.all

  end

  def update
    @task = Task.find(params[:id])
    if params[:status] === false
    @task.update(status: true)
  else
    @task.update(status: false)
  end
    respond_to do |format|
      format.html{
    redirect_to tasks_path
    flash[:notice] = "Task edited"
      }
      format.js{
    puts "$" * 100
    puts params.inspect
    puts "$" * 100
      }
    end
   
  end

  def index
    @tasks = Task.all
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
      respond_to do |format|
        format.html{
          redirect_to root_path
        }
        format.js{}
      end
    
  end


  private

  def task_params
    params.permit(:title, :deadline, :description)
  end

  def category_params
    params.require(:Category)
  end

end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/views/home/index.html.erb
<h1 class="text-center mb-4">Welcome to my todolist app</h1>
<%= render 'layouts/task_form'  %>
<div class="container">
  <ul>
  <% @categories.each do  |category|%>
  <li><%= category.title  %></li>
  <div class="card">
    <ul>
      <% category.tasks.each do |task| %>
      <li id="list">
        <%= task.title  %>
        <% unless task.deadline.nil? %>
          , to read: <%= task.deadline.strftime('%D')  %>
        <% end %>
        <%=link_to ("<i class='fas fa-trash-alt'></i>").html_safe , task_path(task.id), method: :delete, remote: true%>
        <%=check_box_tag :task, 1, false, data: {remote: true, url: url_for(controller: "tasks", action: "update", id: task.id), params: {id: task.id, status: task.status}.to_param, method: "put"} %>
      </li>
      <% end %>
    </ul>
  </div>
  <% end %>
  </ul>
</div>

<div class="container">
  <div class="row">
    <% @tasks.each do |task|  %>
      <div class="card col-3">
        <% unless task.image.nil? %>
          <%= image_tag task.image, class: "rounded-circle" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<p class="success"><%= success %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <%= link_to "Sandbox App", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      <% unless user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "New task", new_task_path, class: "nav-link" %>
      </li>
       <li class="nav-item">
        <%= link_to "Emails", emails_path, class: "nav-link" %>
      </li>
      
    </ul>
        <img class="rounded-circle" height="50px" width="50px" src="http://digitalspyuk.cdnds.net/17/25/320x320/square-1498216547-avatar-neytiri.jpg">
  </div>
</nav>

app/views/layouts/_task_form.html.erb
<div class="container">

  <div class="row ml-3">
      <div class="offset-md-3 col-md-6 offset-md-3">
          <%= form_tag(tasks_path, method: "post", class: "form", id: "contact-form", remote: true)  do %>
              <div class="form-group">
                  <%= label_tag "Task", nil, class: "form-label" %>
                  <%= text_field_tag :title, nil, class: "form-control", placeholder: "Buy burgers" %>
              </div>
              <div class="form-group">
                  <%= label_tag "Deadline", nil, class: "form-label" %>
                  <%= date_field_tag :deadline, nil, class: "form-control" %>

              </div>
              <div class="form-group">
                  <%= label_tag "Category", nil, class: "form-label" %>
                  <%= select_tag "Category", options_from_collection_for_select(@categories, "id", "title", "1"), class: "form-control"  %>
              </div>

              <div class="text-center">
                  <%= submit_tag("Create task", class: "btn btn-start-order") %>
              </div>
          <%end%>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodolistApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <script src="https://kit.fontawesome.com/48ba21fe93.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar'  %>
    <%= render 'layouts/flash'  %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_task.html.erb
<li><%= task.title %>
	<% unless task.deadline.nil? %>
          , to read: <%= task.deadline.strftime('%D') %>
      <% end %>
</li>

app/views/tasks/create.js.erb
console.log("<%=@category.id%>")


$("<%= j render 'task', task: @task%>").appendTo("#list");

app/views/tasks/destroy.js.erb
alert("Are you sure???");
$("#list").remove()

app/views/tasks/index.html.erb
<% if user_signed_in? %>

  <%= render 'task_list'  %>

<% end %>

<%= link_to "Create a new task", new_task_path, class: "btn btn-info"  %>

app/views/tasks/update.js.erb
$("#list").css("background-color", "#3366ff")